using UnityEngine;

public class EventsSFX : MonoBehaviour
{
    #region VARIABLES

    [SerializeField] private ParticleSystem particleSystem;

    #endregion
    void OnEnable()
    {
        EventsGameManager.OnEnterKeyPressed += StartParticleSystem;

        EventsGameManager.OnEscapeKeyPressed += StopParticleSystem;
    }


    void OnDisable()
    {
        EventsGameManager.OnEnterKeyPressed -= StartParticleSystem;

        EventsGameManager.OnEscapeKeyPressed -= StopParticleSystem;
    }

    private void Awake()
    {
        StopParticleSystem();
    }

    private void StartParticleSystem()
    {
        particleSystem.Play();
    }
    
    private void StopParticleSystem()
    {
        particleSystem.Stop();
    }
}
